### ISSUE TITLE
Update meeting times (Spring 2016)

### ISSUE THREAD

**Issue by TangentFoxy** [CSCE/website#6]
As soon as possible next semester, let's get the site updated to whatever the meeting times end up being. Use Doodle to get people's scheduling: http://doodle.com/

~~@stevenwashere What was the app you were having us use to try to set up a meeting time this semester? Or was it someone else? I'd like to have it noted down so we're ready to use it again.~~

**Comment by ghost** [comment]
Doodle js a great scheduling web application.

**Comment by TangentFoxy** [comment]
Thank you!

**Comment by TangentFoxy** [comment]
@Alofoxx _waves_ Thanks.
